# Generated by Django 2.1.5 on 2019-02-05 19:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(default='', max_length=30)),
                ('lastName', models.CharField(default='', max_length=40)),
                ('email', models.CharField(default='some@ema.il', max_length=32)),
                ('middleName', models.CharField(default='', max_length=30)),
                ('creationTime', models.DateTimeField(default=datetime.datetime(2019, 2, 5, 19, 59, 46, 91308, tzinfo=utc))),
                ('phoneNumber', models.CharField(default='', max_length=20)),
                ('profilePic', models.CharField(default='', max_length=50)),
                ('lastLogin', models.DateTimeField(default=datetime.datetime(2019, 2, 5, 19, 59, 46, 91308, tzinfo=utc))),
                ('registrationToken', models.CharField(default='', max_length=50)),
                ('rating', models.FloatField(default=5.0)),
                ('IdCard', models.CharField(default='123456', max_length=50)),
                ('enablePrivacy', models.BooleanField(default=True)),
                ('userTypeId', models.SmallIntegerField(default=1)),
                ('verificationId', models.SmallIntegerField(default=0)),
                ('googleId', models.CharField(default='    ', max_length=50)),
                ('avatar', models.CharField(default='default.jpg', max_length=250)),
            ],
        ),
    ]
